version: "3.7"
services:
  db2:
    image: icr.io/db2_community/db2:latest
    privileged: true    # Should not be necessary
    ports:
      - "50000:50000"
    environment:
      LICENSE: accept
      DB2INSTANCE: db2inst1
      DB2INST1_PASSWORD: password
      DBNAME: testdb
      BLU: false
      ENABLE_ORACLE_COMPATIBILITY: false
      UPDATEAVAIL: NO
      TO_CREATE_SAMPLEDB: false
      REPODB: false
      IS_OSXFS: true
      PERSISTENT_HOME: true
      HADR_ENABLED: false
      ETCD_ENDPOINT: 
      ETCD_USERNAME:
      ETCD_PASSWORD:
